name: Build

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        
      - name: Run Build
        run: |
          npm ci
          npm run build
          
      - name: SSH Remote & start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 stop 0
            cd git-daehyun/highthon-server
            sudo git pull
            npm install
            npm run build
            pm2 start 0
